---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Phoradentron interactions


<!-- badges: start -->
<!-- badges: end -->

Instructions to run the code used to generate results in the manuscript “Interaction network of *Phoradendron* and its hosts and the influence of phylogenetic, geographic, and environmental factors on the probability of interaction”

All analyses were run in a computer with the following specifications:

CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GH with 64GB RAM
You'll still need to render `README.Rmd` regularly, to keep `README.md` up-to-date.

File description and steps:

- Download repository from GitHub at https://anonymous.4open.science/r/phoradendron_interactions/

- The script directory contains src scripts (with helper functions) and
numerated scripts

- All the outputs of the scripts will appear in the *data* directory

- In order to have replicability you need to run scripts sequentially and store
